# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialID', models.CharField(max_length=100, unique=True, verbose_name='\u6750\u6599\u6807\u53f7')),
                ('materialName', models.CharField(max_length=100, verbose_name='\u6750\u6599\u540d\u79f0')),
                ('materialNum', models.IntegerField(verbose_name='\u5e93\u5b58\u6750\u6599\u91cf')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputDateTime', models.DateTimeField(auto_now_add=True, verbose_name='\u5165\u5e93\u65f6\u95f4')),
                ('inputOperator', models.CharField(max_length=100, verbose_name='\u64cd\u4f5c\u4eba\u5458')),
                ('inputNum', models.IntegerField(verbose_name='\u5165\u5e93\u91cf')),
                ('inputMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inut_material', to='repetory_api.Material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outputDateTime', models.DateTimeField(auto_now_add=True, verbose_name='\u51fa\u5e93\u65f6\u95f4')),
                ('outputOperator', models.CharField(max_length=100, verbose_name='\u64cd\u4f5c\u4eba\u5458')),
                ('outputNum', models.IntegerField(verbose_name='\u51fa\u5e93\u91cf')),
                ('outputMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_material', to='repetory_api.Material')),
            ],
        ),
    ]
