# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repetory_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialinput',
            name='inputMaterial',
        ),
        migrations.RemoveField(
            model_name='materialoutput',
            name='outputMaterial',
        ),
        migrations.DeleteModel(
            name='MaterialInput',
        ),
        migrations.DeleteModel(
            name='MaterialOutput',
        ),
    ]
