# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repetory_api', '0002_auto_20170608_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(null=True, verbose_name='\u63cf\u8ff0'),
        ),
    ]
