# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repetory_api', '0004_materialinput_materialoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinput',
            name='inputMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_material', to='repetory_api.Material'),
        ),
    ]
