# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repetory_api', '0005_auto_20170608_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinput',
            name='inputMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputMaterial', to='repetory_api.Material'),
        ),
        migrations.AlterField(
            model_name='materialoutput',
            name='outputMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputMaterial', to='repetory_api.Material'),
        ),
    ]
