# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repetory_api', '0009_auto_20170609_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='matrialUnit',
            new_name='materialUnit',
        ),
    ]
