# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repetory_api', '0011_auto_20170609_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialinput',
            name='materialMark',
        ),
        migrations.AddField(
            model_name='material',
            name='materialMark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6750\u6599\u578b\u53f7'),
        ),
    ]
