# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repetory_api', '0012_auto_20170609_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialinput',
            old_name='materailYear',
            new_name='materialYear',
        ),
    ]
