# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repetory_api', '0013_auto_20170609_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinput',
            name='materialYear',
            field=models.DateField(blank=True, null=True, verbose_name='\u6750\u6599\u5e74\u4efd'),
        ),
    ]
