# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repetory_api', '0014_auto_20170609_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialoutput',
            name='outputNum',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='\u51fa\u5e93\u91cf'),
        ),
    ]
