# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repetory_api', '0015_auto_20170609_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='materialID',
            field=models.CharField(max_length=100, unique=True, verbose_name='\u6750\u6599\u6807\u53f7'),
        ),
        migrations.AlterField(
            model_name='material',
            name='materialNum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u5e93\u5b58\u6750\u6599\u91cf'),
        ),
        migrations.AlterField(
            model_name='materialinput',
            name='inputNum',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='\u5165\u5e93\u91cf'),
        ),
    ]
