# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repetory_api', '0016_auto_20170705_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinput',
            name='inputMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repetory_api.Material'),
        ),
    ]
