# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repetory_api', '0017_auto_20170705_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinput',
            name='inputNum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u5165\u5e93\u91cf'),
        ),
    ]
