# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repetory_api', '0019_auto_20170705_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialoutput',
            name='materialBand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6750\u6599\u54c1\u724c'),
        ),
        migrations.AddField(
            model_name='materialoutput',
            name='materialOriginal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6750\u6599\u539f\u4ea7\u5730'),
        ),
        migrations.AddField(
            model_name='materialoutput',
            name='materialPostion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6750\u6599\u4f4d\u7f6e'),
        ),
        migrations.AddField(
            model_name='materialoutput',
            name='materialState',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6750\u6599\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='materialoutput',
            name='materialUnit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u6750\u6599\u5355\u4f4d\u539f\u503c'),
        ),
        migrations.AddField(
            model_name='materialoutput',
            name='materialUser',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6750\u6599\u53bb\u5411'),
        ),
        migrations.AddField(
            model_name='materialoutput',
            name='materialYear',
            field=models.DateField(blank=True, null=True, verbose_name='\u6750\u6599\u5e74\u4efd'),
        ),
        migrations.AlterField(
            model_name='materialinput',
            name='materialUnit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u6750\u6599\u5355\u4f4d\u539f\u503c'),
        ),
        migrations.AlterField(
            model_name='materialoutput',
            name='outputMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repetory_api.Material'),
        ),
        migrations.AlterField(
            model_name='materialoutput',
            name='outputNum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u51fa\u5e93\u91cf'),
        ),
    ]
