# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repetory_api', '0020_auto_20170705_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinput',
            name='inputDateTime',
            field=models.DateField(auto_now_add=True, verbose_name='\u5165\u5e93\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='materialoutput',
            name='outputDateTime',
            field=models.DateField(auto_now_add=True, verbose_name='\u51fa\u5e93\u65f6\u95f4'),
        ),
    ]
