# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repetory_api', '0022_material_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialinput',
            name='materialBand',
        ),
        migrations.RemoveField(
            model_name='materialinput',
            name='materialOriginal',
        ),
        migrations.RemoveField(
            model_name='materialinput',
            name='materialPostion',
        ),
        migrations.RemoveField(
            model_name='materialinput',
            name='materialState',
        ),
        migrations.RemoveField(
            model_name='materialinput',
            name='materialUnit',
        ),
        migrations.RemoveField(
            model_name='materialinput',
            name='materialYear',
        ),
        migrations.RemoveField(
            model_name='materialoutput',
            name='materialBand',
        ),
        migrations.RemoveField(
            model_name='materialoutput',
            name='materialOriginal',
        ),
        migrations.RemoveField(
            model_name='materialoutput',
            name='materialPostion',
        ),
        migrations.RemoveField(
            model_name='materialoutput',
            name='materialState',
        ),
        migrations.RemoveField(
            model_name='materialoutput',
            name='materialUnit',
        ),
        migrations.RemoveField(
            model_name='materialoutput',
            name='materialYear',
        ),
        migrations.AddField(
            model_name='material',
            name='materialBand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6750\u6599\u54c1\u724c'),
        ),
        migrations.AddField(
            model_name='material',
            name='materialOriginal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6750\u6599\u539f\u4ea7\u5730'),
        ),
        migrations.AddField(
            model_name='material',
            name='materialPostion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6750\u6599\u4f4d\u7f6e'),
        ),
        migrations.AddField(
            model_name='material',
            name='materialState',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6750\u6599\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='material',
            name='materialUnit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u6750\u6599\u5355\u4f4d\u539f\u503c'),
        ),
        migrations.AddField(
            model_name='material',
            name='materialYear',
            field=models.DateField(blank=True, null=True, verbose_name='\u6750\u6599\u5e74\u4efd'),
        ),
    ]
